name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: '0'
    - name: Create all local branches # So that the git bundle contains all branch pointers
      continue-on-error: true
      run: |
        cd Botania && (for b in `git branch -r | grep -v -- '->'`; do git branch --track ${b##origin/} $b; done)
    - name: Install dependencies
      run: |
        sudo apt-get install -y make genisoimage
    - name: Build ISO
      run: |
        make BotaniaCD.iso
    - name: Sign
      env:
        SIGNING_KEY: ${{ secrets.VIOLET_MOON_SIGNING_KEY }}
      if: ${{ env.SIGNING_KEY != '' }}
      run: |
        echo "${SIGNING_KEY}" | gpg --import -
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign BotaniaCD.iso
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: BotaniaCD
        path: |
          BotaniaCD.iso
          BotaniaCD.iso.asc
