name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: '0'
    - name: Create all local branches # So that the git bundle contains all branch pointers
      run: |
        # Filter out 1.20.x which will include both `origin/1.20.x` and `origin/HEAD -> origin/1.20.x`
        cd Botania && (for b in `git branch -r | grep -v -- '1.20.x'`; do git branch --track ${b##origin/} $b; done)
    - name: Install dependencies
      run: |
        sudo apt-get install -y make
    - name: Build ISO
      run: |
        make build
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: BotaniaCD
        path: |
          audio
          build
